version: "3.4"
services: 
  httpd:
    build: .
    hostname: "httpd"
    ports:
    - "80:80"
volumes:
   - /usr/local/apache2/htdocs:/data_test/tomcat-docker/
   - /usr/local/apache2/conf/httpd.conf:/data_test/tomcat-docker/httpd.conf
